language: cpp
os:
  - linux
sudo: required
dist: trusty
compilers:
  - g++-5
  - clang
addons:
  apt:
    sources:
    - ppa:george-edison55/cmake-3.x
    - ppa:ubuntu-toolchain-r/test
    packages:
    - software-properties-common
    - gcc-5
    - g++-5
    - cmake
    - cmake-data
    - clang
script:
  - mkdir build && cd build && cmake .. && cmake --build .
