language: cpp
os:
  - linux
sudo: required
dist: trusty
compilers:
  - g++-6
  - clang
addons:
  apt:
    sources:
    - sourceline: 'ppa:adrozdoff/cmake'
    - sourceline: 'ppa:ubuntu-toolchain-r/test'
    - software-properties-common
    packages:
    - gcc-6
    - g++-6
    - cmake
    - cmake-data
    - clang
script:
  - mkdir build && cd build && cmake .. && cmake --build .
