language: cpp
os:
  - linux
sudo: false
dist: trusty
addons:
  apt:
    sources:
    - sourceline: 'ppa:adrozdoff/cmake'
    - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
    - gcc-6
    - g++-6
    - cmake
    - cmake-data
    - clang
matrix:
  include:
  - env: CXX=g++-6 CC=gcc-6
  - env: CXX=clang++ CC=clang
script:
  - mkdir build && cd build && cmake .. && cmake --build .
