language: cpp
os:
  - linux
sudo: required
dist: trusty
before_install:
  - sudo apt-get install software-properties-common
  - sudo add-apt-repository ppa:george-edison55/cmake-3.x --yes
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test --yes
  - sudo apt-get update --yes
install:
  - sudo apt-get install gcc-5 g++-5 --yes
  - sudo apt-get install cmake cmake-data --yes
script:
  - export CXX=g++-5
  - mkdir build && cd build && cmake .. && cmake --build .
